name: Lint

on: [push, pull_request, workflow_dispatch]

env:
  FORCE_COLOR: 1

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:

    runs-on: ubuntu-latest

    name: Lint

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: hynek/setup-cached-uv@v2

    - name: Lint
      run: uvx --with tox-uv tox -e lint --python python3.13
      env:
        PRE_COMMIT_COLOR: always

    - name: Mypy
      run: uvx --with tox-uv tox -e mypy
