name: Lint

on: [push, pull_request, workflow_dispatch]

env:
  FORCE_COLOR: 1

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:

    runs-on: ubuntu-24.04

    name: Lint

    steps:
    - uses: actions/checkout@v4

    - name: pre-commit
      uses: tox-dev/action-pre-commit-uv@v1

    - name: Install uv
      uses: hynek/setup-cached-uv@v2

    - name: check-manifest
      run: uvx check-manifest

    - name: Mypy
      run: uvx --with tox-uv tox -e mypy
