name: Test

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

env:
  FORCE_COLOR: 1

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [
          "ubuntu-latest",
        ]
        python-version: [
          "pypy-3.8",
          "pypy-3.7",
          "3.11-dev",
          "3.10",
          "3.9",
          "3.8",
          "3.7",
        ]
        include:
        - python-version: "3.7"
          PYTHONOPTIMIZE: 1
          REVERSE: "--reverse"
        - python-version: "3.8"
          PYTHONOPTIMIZE: 2
        # Include new variables for Codecov
        - os: ubuntu-latest
          codecov-flag: GHA_Ubuntu

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} Python ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: ".ci/*.sh"

    - name: Build system information
      run: python3 .github/workflows/system-info.py

    - name: Install Linux dependencies
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        .ci/install.sh
      env:
        GHA_PYTHON_VERSION: ${{ matrix.python-version }}

    - name: Build
      run: |
        .ci/build.sh

    - name: Docs
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        python3 -m pip install furo sphinx-copybutton sphinx-issues sphinx-removed-in sphinxext-opengraph
        make doc

  success:
    permissions:
      contents: none
    needs: build
    runs-on: ubuntu-latest
    name: Test Successful
    steps:
      - name: Success
        run: echo Test Successful
